### ISSUE TITLE
no push notification

### ISSUE THREAD

**Issue by Angonikro** [nitanmarcel/cinny-click-packaging#5] opened 2022-05-09 11:53 UTC
push notification don't work . redmi note 9 pro

**Comment by nitanmarcel** [comment] 2022-05-09 12:05
Please log-in to [app.element.org](https://app.element.io/) from your pc, and check if the global notifications options are set to on or noisy. Also if you have FluffyChat installed, try to uninstall it.

Thanks.

**Comment by CactiChameleon9** [comment] 2022-05-10 16:36
@nitanmarcel Why might uninstalling fluffychat help? Is there some incompatibility between the 2?

**Comment by nitanmarcel** [comment] 2022-05-10 16:48
> @nitanmarcel Why might uninstalling fluffychat help? Is there some incompatibility between the 2?

There could be. I think there was another user that had issues with the two installed.

**Comment by CactiChameleon9** [comment] 2022-05-11 07:10
> > @nitanmarcel Why might uninstalling fluffychat help? Is there some incompatibility between the 2?
> 
> There could be. I think there was another user that had issues with the two installed.

Is there anything I can do to help debug that?

**Comment by nitanmarcel** [comment] 2022-05-11 07:25
> > > @nitanmarcel Why might uninstalling fluffychat help? Is there some incompatibility between the 2?
> > 
> > 
> > There could be. I think there was another user that had issues with the two installed.
> 
> Is there anything I can do to help debug that?

Could have something to do with fluffy silencing the notification or blocking it completely. You can look in `.cache/upstart/ubuntu-push-client.log` too see what json value matrix sends and what gets parsed by cinny. Any failures are in `.cache/upstart/untrusted-helper-*cinny*.log`

**Comment by mdehollander** [comment] 2022-06-05 08:15
I have the same thing over here. I had fluffychat and pantalaimon installed before. Global notification in element set to noisy. I don't see any messages in any of these log files. I think the app makes a sound when active and a message arrives, but no notifications. Did anyone figure out how to get notifications working. Would be nice :)

**Comment by digi6622** [comment] 2022-06-08 10:31
Same issue on Vollaphone (Ubuntu Touch): Fresh installation of the phone without installing any apps (just included system apps). In previous installations I have remarked that the push-urls of cinny differs to the Fluffychat url . Could that be a hint ?

**Comment by nitanmarcel** [comment] 2022-06-08 10:45
> Same issue on Vollaphone (Ubuntu Touch): Fresh installation of the phone without installing any apps (just included system apps). In previous installations I have remarked that the push-urls of cinny differs to the Fluffychat url . Could that be a hint ?

Push works for me without any issues. I need logs from users that don't have them working

https://github.com/nitanmarcel/cinny-click-packaging/issues/5#issuecomment-1123282907

**Comment by digi6622** [comment] 2022-06-08 11:38
I hope I found the right part:
`2022/06/08 13:31:08.290738 ERROR GetWindowStack call returned org.freedesktop.DBus.Error.ServiceUnknown: The name com.canonical.Unity.WindowStack was not provided by any .service files`

**Comment by nitanmarcel** [comment] 2022-06-08 11:44
> I hope I found the right part: `2022/06/08 13:31:08.290738 ERROR GetWindowStack call returned org.freedesktop.DBus.Error.ServiceUnknown: The name com.canonical.Unity.WindowStack was not provided by any .service files`

unrelated.

I need the matrix response and the server response from `.cache/upstart/ubuntu-push-client.log`

If there's any errors in the push server it will appear here:


```
.cache/upstart/untrusted-helper-*cinny*.log
```

What you need to look in `.cache/upstart/ubuntu-push-client.log` if the matrix response has the `["message"]["devices"][0]["tweaks"]["sound"]` set to "default" or anything else. and if the push server response has `["notification"]["card"]["popup"]` set to true

**Comment by digi6622** [comment] 2022-06-08 13:42
First of all here is my ubuntu-pushclient.log:
`2022/06/08 11:27:43.335667 ERROR session error'ed out with read tcp 100.117.200.9:32882->188.166.175.79:5001: read: connection reset by peer
2022/06/08 11:29:27.220110 INFO connectivity check passed.
2022/06/08 11:33:24.472080 ERROR session error'ed out with read tcp 100.117.200.9:32884->188.166.175.79:5001: read: connection reset by peer
2022/06/08 11:40:42.336460 ERROR session error'ed out with read tcp 100.117.200.9:32888->188.166.175.79:5001: read: connection reset by peer
2022/06/08 11:47:33.931712 ERROR session error'ed out with read tcp 100.117.200.9:32890->188.166.175.79:5001: read: connection reset by peer
2022/06/08 11:57:49.434976 ERROR session error'ed out with read tcp 100.117.200.9:32892->188.166.175.79:5001: read: connection reset by peer
2022/06/08 12:08:00.882130 INFO connectivity check passed.
2022/06/08 12:08:55.044083 ERROR session error'ed out with read tcp 100.117.200.9:32894->188.166.175.79:5001: read: connection reset by peer
2022/06/08 12:14:36.044693 ERROR not connected after 1m0s; giving up
2022/06/08 12:22:24.371002 ERROR session error'ed out with read tcp 100.117.200.9:32898->188.166.175.79:5001: read: connection reset by peer
2022/06/08 12:25:43.259667 ERROR not connected after 1m0s; giving up
2022/06/08 12:32:56.341726 ERROR session error'ed out with read tcp 100.117.200.9:32912->188.166.175.79:5001: read: connection reset by peer
2022/06/08 12:35:51.699558 INFO connectivity check passed.
2022/06/08 12:36:48.063306 ERROR not connected after 1m0s; giving up`

**Comment by nitanmarcel** [comment] 2022-06-08 16:22
> First of all here is my ubuntu-pushclient.log: `2022/06/08 11:27:43.335667 ERROR session error'ed out with read tcp 100.117.200.9:32882->188.166.175.79:5001: read: connection reset by peer 2022/06/08 11:29:27.220110 INFO connectivity check passed. 2022/06/08 11:33:24.472080 ERROR session error'ed out with read tcp 100.117.200.9:32884->188.166.175.79:5001: read: connection reset by peer 2022/06/08 11:40:42.336460 ERROR session error'ed out with read tcp 100.117.200.9:32888->188.166.175.79:5001: read: connection reset by peer 2022/06/08 11:47:33.931712 ERROR session error'ed out with read tcp 100.117.200.9:32890->188.166.175.79:5001: read: connection reset by peer 2022/06/08 11:57:49.434976 ERROR session error'ed out with read tcp 100.117.200.9:32892->188.166.175.79:5001: read: connection reset by peer 2022/06/08 12:08:00.882130 INFO connectivity check passed. 2022/06/08 12:08:55.044083 ERROR session error'ed out with read tcp 100.117.200.9:32894->188.166.175.79:5001: read: connection reset by peer 2022/06/08 12:14:36.044693 ERROR not connected after 1m0s; giving up 2022/06/08 12:22:24.371002 ERROR session error'ed out with read tcp 100.117.200.9:32898->188.166.175.79:5001: read: connection reset by peer 2022/06/08 12:25:43.259667 ERROR not connected after 1m0s; giving up 2022/06/08 12:32:56.341726 ERROR session error'ed out with read tcp 100.117.200.9:32912->188.166.175.79:5001: read: connection reset by peer 2022/06/08 12:35:51.699558 INFO connectivity check passed. 2022/06/08 12:36:48.063306 ERROR not connected after 1m0s; giving up`

that looks like an issue with the push client. not with the app.

Not on UT rn, I would have given an example how would it look.

I guess you could do `tail -f .cache/upstart/ubuntu-push-client.log` then send yourself a message from your pc. Something which looks like a json would be written to the file

**Comment by mdehollander** [comment] 2022-06-08 18:48
For me there is nothing appearing in `ubuntu-push-client.log` when I trigger a notification by sending a message with another account. It does trigger a desktop notification.

In the push client log file there are json strings for telegram notification for example:
```
2022/06/08 20:24:21.328546 INFO teleports.ubports_push_0.14.0 helper output: {
    "notification": {
        "card": {
            "actions": [
...
```

coming from the teleports helper. There is a helper for cinny in `.local/share/ubuntu-push-client/helpers/cinny.nitanmarcel_push_2.0.3.json`.

The contents of this push config file is different as for my other application with working notification. There it contains only the name of the executable, not the app_id:

```
#.local/share/ubuntu-push-client/helpers/teleports.ubports_push_0.14.0.json
{
    "exec": "push"
}

# .local/share/ubuntu-push-client/helpers/cinny.nitanmarcel_push_2.0.3.json
{
    "exec": "push",
    "app_id": "cinny.nitanmarcel_cinny"
}
```

Hope this helps fixing this issue.

**Comment by nitanmarcel** [comment] 2022-06-08 18:58
This is all it has? There should be more. in the cinny object there should be more values. also you need to check both the matrix response and push response. which should appear in `ubuntu-push-client.log `.

If they don't appear then probably it's an error you can get from `cat .cache/upstart/untrusted-helper-*cinny*.log`

```
# .local/share/ubuntu-push-client/helpers/cinny.nitanmarcel_push_2.0.3.json
{
    "exec": "push",
    "app_id": "cinny.nitanmarcel_cinny"
}
```

Also matrix delays the notifications a little bit

**Comment by digi6622** [comment] 2022-06-08 20:28
> 

I have tried the tail -f command while sending a message from another device. The output was nothing.

**Comment by mdehollander** [comment] 2022-06-10 18:41
>also you need to check both the matrix response and push response. which should appear in ubuntu-push-client.log .
> If they don't appear then probably it's an error you can get from cat .cache/upstart/untrusted-helper-*cinny*.log

Nothing in both files unfortunately. The untrusted does not exist even. Is there a way to see if the push service for cinny is active on the device or so?

Not sure if it makes a differences, but I am connected not to the main matrix server, but to a home server. Should be ok in theory of course, but just thinking what could be different in our situations.

**Comment by digi6622** [comment] 2022-06-11 07:59
Right, same behavior on my phone.
If I understand the push-notification procedure correctly:
Our phones send a token to the developer (here: nitanmarcel) and a token to ubports server. Both are aligned with each other and the ubports server sends the push notification to our phones.
But if I compare the ubport addresses between Cinny and for example Fluffychat (another Matrix client), both are different !
The push notification from Fluffychat works without problems.

@mdehollander:
I connect to a home server too. This should be a problem. Another members/clients of my matrix instance get notifications (on Android or Sailfish). Notifications are handled exclusively between OS provider and developer.

**Comment by mdehollander** [comment] 2022-06-13 14:26
A new observation. When the app is active it does make a sound when a new message comes in, but i dont trace it in the log files. And there is nothing in the notification menu.

**Comment by nitanmarcel** [comment] 2022-06-13 17:05
> A new observation. When the app is active it does make a sound when a new message comes in, but i dont trace it in the log files. And there is nothing in the notification menu.

That means the push client get's the notification. So probably the issue is here https://github.com/nitanmarcel/cinny-click-packaging/blob/708025077724d422ae2b9a9541e5152d641045b5/push/push.cpp#L53

**Comment by nitanmarcel** [comment] 2022-06-13 17:16
> mdehollander

Is the message a private message, room, encrypted unecrypted?

**Comment by playforvoices1** [comment] 2022-06-14 07:56
Volla Phone Cinny user here without push notifications. I have a question to the ports / url configuration. I'm behind a very strict OPNsense firewall at home. Is the push notification on Cinny related to a special port?

**Comment by nitanmarcel** [comment] 2022-06-14 10:18
> Volla Phone Cinny user here without push notifications. I have a question to the ports / url configuration. I'm behind a very strict OPNsense firewall at home. Is the push notification on Cinny related to a special port?

We are using the same matrix API for push notifications as fluffy does. If that works probably it's just the way I'm parsing it in the push client.

C++ is still a new language for me so most likely something I'm doing wrong and it doesn't show a notification.

An user above said that they still get sound if the application is open but not popup. Is the same thing for you? With the app suspended.

For reference
https://github.com/nitanmarcel/cinny-click-packaging/blob/main/patches/0008-Set-push-notifications-to-UTs-push-hook.patch
https://github.com/nitanmarcel/cinny-click-packaging/blob/main/push/push.cpp

https://spec.matrix.org/unstable/push-gateway-api/

**Comment by nitanmarcel** [comment] 2022-06-14 10:33
My phone doesn't seem to boot UT for some reason. I'll have to backup my Droidian image then reflash everything from 0 before I further look into this issue.

Currently nothing comes in my mind why I had push notifications when I was developing the wrapper

**Comment by nitanmarcel** [comment] 2022-06-14 10:39
Ah, actually I see the issue. Will fix it later today. Looks like I also have to regenerate some patches.

**Comment by nitanmarcel** [comment] 2022-06-14 10:52
@Angonikro @CactiChameleon9 @playforvoices1 @mdehollander  @digi6622 


Looks like the reason I got push notifications before is because I already registered for them. For some reason I didn't ran the push registration so it was never active to begin with.

Please download the latest ci builds from here once they are finished and report back.
https://gitlab.com/nitanmarcel/cinny-click-packaging/-/pipelines/563286286

Thanks.

**Comment by nitanmarcel** [comment] 2022-06-14 11:00
@Angonikro @CactiChameleon9 @playforvoices1 @mdehollander  @digi6622 


Looks like the reason I got push notifications before is because I already registered them. For some reason I didn't ran the promises that requests push notifications so that's why it didn't worked for others.

Please download the latest ci builds from here once they are finished and report back.
https://gitlab.com/nitanmarcel/cinny-click-packaging/-/pipelines/563286286

Thanks.

Click packages (Open then in OpenStore or install them using Ubuntu Tweak Tool) for:

amd64: https://gitlab.com/nitanmarcel/cinny-click-packaging/-/jobs/2587486261/artifacts/file/build/x86_64-linux-gnu/app/cinny.nitanmarcel_2.0.4_amd64.click

arm64: https://gitlab.com/nitanmarcel/cinny-click-packaging/-/jobs/2587486258/artifacts/file/build/aarch64-linux-gnu/app/cinny.nitanmarcel_2.0.4_arm64.click

armhf: https://gitlab.com/nitanmarcel/cinny-click-packaging/-/jobs/2587486253/artifacts/file/build/arm-linux-gnueabihf/app/cinny.nitanmarcel_2.0.4_armhf.click

**Comment by playforvoices1** [comment] 2022-06-14 11:09
> > Volla Phone Cinny user here without push notifications. I have a question to the ports / url configuration. I'm behind a very strict OPNsense firewall at home. Is the push notification on Cinny related to a special port?
> 
> We are using the same matrix API for push notifications as fluffy does. If that works probably it's just the way I'm parsing it in the push client.
> 
> C++ is still a new language for me so most likely something I'm doing wrong and it doesn't show a notification.
> 
> An user above said that they still get sound if the application is open but not popup. Is the same thing for you? With the app suspended.
> 
> For reference https://github.com/nitanmarcel/cinny-click-packaging/blob/main/patches/0008-Set-push-notifications-to-UTs-push-hook.patch https://github.com/nitanmarcel/cinny-click-packaging/blob/main/push/push.cpp
> 
> https://spec.matrix.org/unstable/push-gateway-api/

Yes, sound notification works, but no popup. The app is suspended but allowed to run in background.

**Comment by nitanmarcel** [comment] 2022-06-14 11:18
> > > Volla Phone Cinny user here without push notifications. I have a question to the ports / url configuration. I'm behind a very strict OPNsense firewall at home. Is the push notification on Cinny related to a special port?
> > 
> > 
> > We are using the same matrix API for push notifications as fluffy does. If that works probably it's just the way I'm parsing it in the push client.
> > C++ is still a new language for me so most likely something I'm doing wrong and it doesn't show a notification.
> > An user above said that they still get sound if the application is open but not popup. Is the same thing for you? With the app suspended.
> > For reference https://github.com/nitanmarcel/cinny-click-packaging/blob/main/patches/0008-Set-push-notifications-to-UTs-push-hook.patch https://github.com/nitanmarcel/cinny-click-packaging/blob/main/push/push.cpp
> > https://spec.matrix.org/unstable/push-gateway-api/
> 
> Yes, sound notification works, but no popup. The app is suspended but allowed to run in background.

Should probably be fixed in https://github.com/nitanmarcel/cinny-click-packaging/issues/5#issuecomment-1155032911

The sound notification sound might come from the webapp itself. Which if that's the case I might need to patch it out: https://github.com/cinnyapp/cinny/commit/dc6e153b92adb8b34ace30f7974e6f8e441083b2

**Comment by digi6622** [comment] 2022-06-14 18:13
Thanks Marcel.
But on my volla there is no difference between the download file and the openstore file. Unfortnately there is no notfiication by incoming chats yet.

**Comment by playforvoices1** [comment] 2022-06-16 06:57
> Thanks Marcel. But on my volla there is no difference between the download file and the openstore file. Unfortnately there is no notfiication by incoming chats yet.

Hi Marcel 

The same here on One Plus 5T. Sound notification yes, popup no. I've used your newly provided clickable version from Gitlab.

**Comment by nitanmarcel** [comment] 2022-06-16 07:34
> > Thanks Marcel. But on my volla there is no difference between the download file and the openstore file. Unfortnately there is no notfiication by incoming chats yet.
> 
> Hi Marcel
> 
> The same here on One Plus 5T. Sound notification yes, popup no. I've used your newly provided clickable version from Gitlab.

can you check the logs I mentioned again? Now there should be something in them

**Comment by playforvoices1** [comment] 2022-06-16 07:55
> > > Thanks Marcel. But on my volla there is no difference between the download file and the openstore file. Unfortnately there is no notfiication by incoming chats yet.
> > 
> > 
> > Hi Marcel
> > The same here on One Plus 5T. Sound notification yes, popup no. I've used your newly provided clickable version from Gitlab.
> 
> can you check the logs I mentioned again? Now there should be something in them

Here comes the ubuntu-push-client log out from my One Plus 5T: https://nowtransfer.de/6aca3afa9b9c

**Comment by nitanmarcel** [comment] 2022-06-16 08:01
> > > > Thanks Marcel. But on my volla there is no difference between the download file and the openstore file. Unfortnately there is no notfiication by incoming chats yet.
> > > 
> > > 
> > > Hi Marcel
> > > The same here on One Plus 5T. Sound notification yes, popup no. I've used your newly provided clickable version from Gitlab.
> > 
> > 
> > can you check the logs I mentioned again? Now there should be something in them
> 
> Here comes the ubuntu-push-client log out from my One Plus 5T: https://nowtransfer.de/6aca3afa9b9c

weird. the token should be registered now but matrix doesn't send anything to the push client. 

Have you checked in element to see if you don't have notifications silenced globally?

Also play with the settings in cinny. Make sure you've set the room notifications to All Messages and not Global

**Comment by playforvoices1** [comment] 2022-06-16 08:09
> > > > > Thanks Marcel. But on my volla there is no difference between the download file and the openstore file. Unfortnately there is no notfiication by incoming chats yet.
> > > > 
> > > > 
> > > > Hi Marcel
> > > > The same here on One Plus 5T. Sound notification yes, popup no. I've used your newly provided clickable version from Gitlab.
> > > 
> > > 
> > > can you check the logs I mentioned again? Now there should be something in them
> > 
> > 
> > Here comes the ubuntu-push-client log out from my One Plus 5T: https://nowtransfer.de/6aca3afa9b9c
> 
> weird. the token should be registered now but matrix doesn't send anything to the push client.
> 
> Have you checked in element to see if you don't have notifications silenced globally?
> 
> Also play with the settings in cinny. Make sure you've set the room notifications to All Messages and not Global

I've checked the setting inside Cinny. The notification of the rooms were set to Global. I take them now to All Messages. At Element on Android, all notifications are shown. 

Update: I've got new messages, but sound notification only. No popup. So all remain the same. I will switch to mobile data now to prevent a port blocking by the firewall. 

Update: Also with active mobile data connection, only sound notification. No popup.

**Comment by playforvoices1** [comment] 2022-06-16 09:25
Did you know which IP addresses the push notification is using backwards from the server to the client? So you can investigate if the push arrives in the phone but will not shown because of a sysinternal / code issue. 

Here, for example, the TelePorts App push: https://nowtransfer.de/b3bc995720cf

**Comment by nitanmarcel** [comment] 2022-06-16 09:34
> Did you know which IP addresses the push notification is using backwards from the server to the client? So you can investigate if the push arrives in the phone but will not show because of a sysinternal / code issue.

I'm running Droidian atm but I'll switch to UT again to fix the issue.

**Comment by nitanmarcel** [comment] 2022-06-16 13:13
FIxed in https://github.com/nitanmarcel/cinny-click-packaging/commit/4086f92a08e72f763d246c8a2af0d6fbe92bae4f

Should be available on Open Store in 1 hour or so.

Sorry it took so long. I had to reflash Ubuntu Touch to see what got broken :)

**Comment by nitanmarcel** [comment] 2022-06-16 13:29
> Did you know which IP addresses the push notification is using backwards from the server to the client? So you can investigate if the push arrives in the phone but will not shown because of a sysinternal / code issue.
> 
> Here, for example, the TelePorts App push: https://nowtransfer.de/b3bc995720cf

Can you update from Open Store try now? Going to reopen this because I have a doubt

**Comment by playforvoices1** [comment] 2022-06-16 13:58
I update the app via Open Store and try. No popup notification. Both on WIFI and mobile data connection.


Am Thu, 16 Jun 2022 06:29:14 -0700, Nitan Alexandru Marcel schrieb:
>> Did you know which IP addresses the push notification is using 
>> backwards from the server to the client? So you can investigate 
>> if the push arrives in the phone but will not shown because of 
>> a sysinternal / code issue.
>> 
>> Here, for example, the TelePorts App push: 
>> https://nowtransfer.de/b3bc995720cf
>
> Can you try now? Going to reopen this because I have a doubt
>

--

**Comment by playforvoices1** [comment] 2022-06-16 14:05
> > Did you know which IP addresses the push notification is using backwards from the server to the client? So you can investigate if the push arrives in the phone but will not shown because of a sysinternal / code issue.
> > Here, for example, the TelePorts App push: https://nowtransfer.de/b3bc995720cf
> 
> Can you update from Open Store try now? Going to reopen this because I have a doubt

I've spoken with the developer from TELEports. He said that you should take a closer look at the Fluffy Chat app. There is a working notification build in. Also, you should use the UBports own Matrix Push Gateway. This will use a different port number than the regular one provided by Matrix.

**Comment by nitanmarcel** [comment] 2022-06-16 14:18
Fixed in https://github.com/nitanmarcel/cinny-click-packaging/commit/4086f92a08e72f763d246c8a2af0d6fbe92bae4f and https://github.com/nitanmarcel/cinny-click-packaging/commit/c03286905b699d7903f3a28b45972a6563391ef0

Will be available in the next openstore release.

Sorry for the inconvenience :)

**Closed as completed by nitanmarcel** 2022-06-16 14:18 UTC
Labels: bug

**Comment by nitanmarcel** [comment] 2022-06-16 14:24
> > > Did you know which IP addresses the push notification is using backwards from the server to the client? So you can investigate if the push arrives in the phone but will not shown because of a sysinternal / code issue.
> > > Here, for example, the TelePorts App push: https://nowtransfer.de/b3bc995720cf
> > 
> > 
> > Can you update from Open Store try now? Going to reopen this because I have a doubt
> 
> I've spoken with the developer from TELEports. He said that you should take a closer look at the Fluffy Chat app. There is a working notification build in. Also, you should use the UBports own Matrix Push Gateway. This will use a different port number than the regular one provided by Matrix.

We already set both the push gateway and that push client. The issue was a patch. A new release is available on OpenStore as we speak that fixes all of this.

**Comment by digi6622** [comment] 2022-06-16 15:24
Great job...thanks.

**Comment by playforvoices1** [comment] 2022-06-16 16:20
> > > > Did you know which IP addresses the push notification is using backwards from the server to the client? So you can investigate if the push arrives in the phone but will not shown because of a sysinternal / code issue.
> > > > Here, for example, the TelePorts App push: https://nowtransfer.de/b3bc995720cf
> > > 
> > > 
> > > Can you update from Open Store try now? Going to reopen this because I have a doubt
> > 
> > 
> > I've spoken with the developer from TELEports. He said that you should take a closer look at the Fluffy Chat app. There is a working notification build in. Also, you should use the UBports own Matrix Push Gateway. This will use a different port number than the regular one provided by Matrix.
> 
> We already set both the push gateway and that push client. The issue was a patch. A new release is available on OpenStore as we speak that fixes all of this.

Thanks a lot. Now it works :)

**Comment by mdehollander** [comment] 2022-06-17 09:34
A big Thanks! Works perfectly here.
